### PR TITLE
added chapter 10: Dynamics UI

### PR DESCRIPTION
**Pull request by fgazzelloni**
Introduction (trivial)

### CODE REVIEW

**Comment by russHyde** [comment]
From the checks, it looks like you are using packages that arent installed on the server. Could you run `usethis::use_package("shinyWidgets")` and similarly for shinythemes and any other packages that are loaded by the chapter but are not in the DESCRIPTION. Then push your updated DESCRIPTION file.

**Comment by fgazzelloni** [comment]
Hello! I have updated the notes for chapter 10, there is also an example in the example folder.

**Comment by russHyde** [comment]
Awesome. Would you like me to remove the draft status on this PR so that we can merge the chapter before the book club?

**Comment by russHyde** [comment]
Thanks

**Review by russHyde — APPROVED** [review]
LGTM

**Pull request merged**
