### PR TITLE
Inclusion of chapter 12

### PR DESCRIPTION
**Pull request by overmar**
This is my RMarkdown from todays presentation.

### CODE REVIEW

**Comment by russHyde** [comment]
The content looks fine. I was a bit worried that there's a lot of the original text in there. The original book has a form of creative-commons license, so that shouldn't be an issue (do you agree @jonthegeek ?)

**Comment by jonthegeek** [comment]
> I was a bit worried that there's a lot of the original text in there. The original book has a form of creative-commons license, so that shouldn't be an issue (do you agree @jonthegeek ?)

The license is specifically Attribution-NonCommercial-NoDerivatives 4.0 International (CC BY-NC-ND 4.0)

The "no derivatives" part means we still need to think about fair use, so we should update this to contain less of the original text, unfortunately. Thanks for the catch, @russHyde!

**Comment by jonthegeek** [comment]
@overmar Can you edit out some of the direct copies from the book? I haven't dug into exactly what's here, but I want to make sure we aren't overdoing it. Perhaps just a short quote + link would suffice?

**Review by jonthegeek — CHANGES_REQUESTED** [review]
@overmar Can you edit out some of the direct copies from the book? I haven't dug into exactly what's here, but I want to make sure we aren't overdoing it. Perhaps just a short quote + link would suffice?

**Comment by tanho63** [comment]
Hiya @overmar ! Just checking in on this one :)

**Comment by jonthegeek** [comment]
We'll let cohort 2 fill in these notes!

**Pull request closed without merging**
