### PR TITLE
add basic-UI chapter; author='Matt Curcio'

### PR DESCRIPTION
**Pull request by russHyde**

### CODE REVIEW

**Comment by russHyde** [comment]
Alongside this book chapter, Matt prepared an R script containing an example shiny app.

I've added an examples/ directory to house that script; this shouldn't affect the rendering of the book.

People could add apps / scripts inside this examples directory to provide further illustrations of the chapters.

Since it won't become part of the book, should I modify the README to explain the purpose of the examples/ directory?

**Comment by russHyde** [comment]
When a user adds an example app that is relevant to a specific chapter, they should add it to:

- `./examples/<chapter_number>-<title_slug>/app.R` if they have made a single app for that chapter
- `./examples/<chapter_number>-<title_slug>/<description>/app.R` if they have made multiple apps for the chapter

... where `<chapter_number>-<title_slug>` matches the chapter title of their .Rmd file

**Comment by tanho63** [comment]
> * `./examples/<chapter_number>-<title_slug>/<description>/app.R` if they have made multiple apps 

I would prefer  * `./examples/<chapter_number>-<title_slug>-<shortdescription>/app.R` instead of subfolders, which I think would be easier to programmatically deploy to a shiny server one day

**Comment by russHyde** [comment]
Agreed. I've updated the README to indicate to future authors where they should put any example apps.

**Review by tanho63 — APPROVED** [review]

**Pull request merged**
