### PR TITLE
add notes on best-practices/guidelines

### PR DESCRIPTION
**Pull request by russHyde**
These are some notes based on the content of CH17 (the guidelines for the part on best-practices).

Hoping to have a discussion rather than a linear run through content.

Feel free to add any questions, interesting observations etc re R and the wider world of software engineering and teamwork

### CODE REVIEW

**Comment by russHyde** [comment]
@tanho63  / @jonthegeek could you review this please. I can't merge it.

**Review by jonthegeek — APPROVED** [review]
This looks great!

It isn't a requirement, but it can be helpful to give blocks unique names (I often include the chapter number to keep them unique) to make debugging easier. It's OK to wait til there's something to debug to add names to existing things, but keep that in mind while you're writing notes for the last chapters.

**Comment by russHyde** [comment]
Thanks. But I don't think there are any blocks in this chapter ... :0)

**Comment by jonthegeek** [comment]
There are a couple at the top... And now that I've merged it, I'm not sure they're supposed to be there.

**Pull request merged**
